// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Data struct {
	Points []*DataPoint `json:"points"`
}

type DataPoint struct {
	Count     int    `json:"count"`
	Timestamp int    `json:"timestamp"`
	Attribute string `json:"attribute"`
}

type NewData struct {
	Points []*NewDataPoint `json:"points"`
}

type NewDataPoint struct {
	Count     int    `json:"count"`
	Timestamp int    `json:"timestamp"`
	Attribute string `json:"attribute"`
}

type NewStatistic struct {
	Duration string   `json:"duration"`
	Interval string   `json:"interval"`
	Mode     string   `json:"mode"`
	Timezone string   `json:"timezone"`
	Data     *NewData `json:"data"`
}

type Statistic struct {
	ID       string `json:"id"`
	Duration string `json:"duration"`
	Interval string `json:"interval"`
	Mode     string `json:"mode"`
	Timezone string `json:"timezone"`
	Data     *Data  `json:"data"`
}
